### ISSUE TITLE
Where is the file resnet.h5?

### ISSUE THREAD

**Issue by ishara133** [yeyupiaoling/VoiceprintRecognition-Tensorflow#1]
Where is the file resnet.h5? I only find the file model_weights.h5

**Comment by yeyupiaoling** [comment]
@ishara133 model_weights.h5 is a pre-training model. Save the resnet.h5 and model_weights.h5 after the training.

**Comment by ChanNuoYan** [comment]
I even can not find the file modle_weights.h5...Did I do sth wrong?^V^

**Comment by yeyupiaoling** [comment]
You have to train for this
