### ISSUE TITLE
若换成我自己的数据，需要变更哪些参数？

### ISSUE THREAD

**Issue by wenku1992abc** [yeyupiaoling/VoiceprintRecognition-Tensorflow#10]
比如，我换了aishell,aidatang等数据，需要修改哪些参数？

1. create_data.py第44~45行的2.04什是谁的时长？换数据需要更改吗？
                # [可能需要修改参数] 音频长度 16000 * 秒数
                wav_len = int(16000 * 2.04)

2.create_data.py第59~60行的 128*128又是什么size?换数据需要更改吗？               
            # [可能需要修改参数] 梅尔频谱shape ，librosa.feature.melspectrogram(y=wav_output, sr=sr, hop_length=256).shape
                    if len(ps) != 128 * 128: continue

还有一个问题就是，模型训练时候可以用上GPU吗？

**Comment by yeyupiaoling** [comment]
@wenku1992abc 那个时长一般是固定的，因为那样刚好是一个正方形。
这个是生成梅尔频谱的接口，shape是经过没梅尔频谱的数据形状

这个得用GPU，CPU很慢

**Comment by wenku1992abc** [comment]
嗯嗯，多谢您的回答
意思是我换数据的话这些参数不用改就可以跑了是吗？

@yeyupiaoling

**Comment by yeyupiaoling** [comment]
正常情况下是不用该的，当然这个参数也不是最好的，如果你想进一步提高准确或者是实际情况限制，你也可以改时长，但是改之后，后面还有很多参数跟着该的。比较麻烦。

**Comment by wenku1992abc** [comment]
> 正常情况下是不用该的，当然这个参数也不是最好的，如果你想进一步提高准确或者是实际情况限制，你也可以改时长，但是改之后，后面还有很多参数跟着该的。比较麻烦。

ok，明白。多谢
