### ISSUE TITLE
用新的code生成数据，label不一样

### ISSUE THREAD

**Issue by wenku1992abc** [yeyupiaoling/VoiceprintRecognition-Tensorflow#11]
![image](https://user-images.githubusercontent.com/33471245/112100331-ede35a80-8bdf-11eb-997e-490321e94b59.png)
如图所示
难道咱们用的不是一批数据集？

**Comment by yeyupiaoling** [comment]
前面15个字符对应上同一个人，你看下代码的做法。

**Comment by wenku1992abc** [comment]
![image](https://user-images.githubusercontent.com/33471245/112100613-57fbff80-8be0-11eb-859e-e90d3f78c1e7.png)
我自己针对我用的数据集修改了一下，请帮忙看下 这样可对？

**Comment by yeyupiaoling** [comment]
@wenku1992abc 只要你做到同一个人，同一个标签就好，前面不用加0.

**Comment by wenku1992abc** [comment]
> @wenku1992abc 只要你做到同一个人，同一个标签就好，前面不用加0.

我是取了字符的中间几位，暂时没有处理0。。带上0可有影响？不影响的话我就不处理了。
转二进制文件我有看到取整数的操作，28行_int64_feature(label)，所以不处理0了也可以吧

**Comment by yeyupiaoling** [comment]
类型转换应该不影响。

**Comment by wenku1992abc** [comment]
> 类型转换应该不影响。

嗯嗯，我就先不处理0了
谢谢啦

**Comment by wenku1992abc** [comment]
@yeyupiaoling 对了，我发现数据并没有855个人，那需要改一下class_dim = 855吗？
这个类别数，必须与真正的speaker数目对应吗？
通过label去重，统计类别数是否可以？
还是说类别数只要在855内就可以？

**Comment by yeyupiaoling** [comment]
可以不用改，只要不超过都可以，但是我一般设置都是跟人的类别数量一致的

**Comment by wenku1992abc** [comment]
> 可以不用改，只要不超过都可以，但是我一般设置都是跟人的类别数量一致的

嗯嗯，多谢

**Comment by wenku1992abc** [comment]
@yeyupiaoling 
hi，請教一下，label必須為數值嗎？
若打标签的时候我想区分数据集
比如aishell的label为aishell_1 aishell_2 ........   
STCMDs的label为STCMD_1 STCMD_2  .......
然后混合一起训练。
这样的标签可以吗？
貌似无法转TFrecord.

**Comment by yeyupiaoling** [comment]
label是分类标签，当然是int数字
你只要做到同一个人同一个标签就好，
任何numpy数据都可以转为TFrecord。

**Comment by wenku1992abc** [comment]
> label是分类标签，当然是int数字
> 你只要做到同一个人同一个标签就好，
> 任何numpy数据都可以转为TFrecord。
好滴~谢谢啦

**Comment by wenku1992abc** [comment]
@yeyupiaolin
train的数据集speaker与test的数据集speaker没有交叠可以吗？
就是语者独立
比如speaker 12345训练  speaker 67测试
训练出来的模型，再拿来做声纹识别

**Comment by yeyupiaoling** [comment]
@wenku1992abc 如果是在訓練中不行，測試集中出現的label，訓練集中必須有。後面訓練結束用的聲紋匹配可以用，因爲那個用的是語音特徵

**Comment by wenku1992abc** [comment]
> @wenku1992abc 如果是在訓練中不行，測試集中出現的label，訓練集中必須有。後面訓練結束用的聲紋匹配可以用，因爲那個用的是語音特徵

哦哦哦，多谢多谢~·

**Comment by wenku1992abc** [comment]
> @yeyupiaoling 
hi,我还想问一下数据集的比例划分。
从你的代码来看是100:1的比例，这个比例有什么讲究吗？

**Comment by yeyupiaoling** [comment]
没有，只要有一定数量的测试集就好

**Comment by wenku1992abc** [comment]
> 没有，只要有一定数量的测试集就好

ok
