### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.api._v2.keras.applications' has no attribute 'ResNet50V2'

### ISSUE THREAD

**Issue by wenku1992abc** [yeyupiaoling/VoiceprintRecognition-Tensorflow#12]
@yeyupiaoling 
hi,请教一下~tensoflow_GPU没有resnet50V2这个网络结构吗？
cpu跑起来很顺畅，只不过有点慢，于是我就去带GPU的机器上跑
可是tensoflow_GPU报错如图所示：
tensoflow_GPU版本2.0.0b0
![image](https://user-images.githubusercontent.com/33471245/112560788-dc33ca00-8e0e-11eb-96ef-d60323e52670.png)

**Comment by yeyupiaoling** [comment]
你安装2.0正式版试试。应该是版本问题

**Comment by wenku1992abc** [comment]
我有尝试两种方法安装tensoflow_GPU2.0.0
1.在线安装pip install tensorflow_GPU,chua出现没有2.0.0版本，我很困惑
![image](https://user-images.githubusercontent.com/33471245/112563946-46e80400-8e15-11eb-9c69-9404080355f2.png)
2.离线安装pip install "tensorflow_gpu-2.0.0-cp37-cp37m-manylinux2010_x86_64.whl"
![image](https://user-images.githubusercontent.com/33471245/112564009-6d0da400-8e15-11eb-9cce-29453a21b68e.png)

**Comment by yeyupiaoling** [comment]
你看下文档吧，感觉都你不熟悉tensorflow 

https://tensorflow.google.cn/install/pip

![image](https://user-images.githubusercontent.com/26297768/112564295-fa50f880-8e15-11eb-9ecc-6b1684b4428e.png)

**Comment by wenku1992abc** [comment]
@yeyupiaoling 
![image](https://user-images.githubusercontent.com/33471245/112564998-3d5f9b80-8e17-11eb-8265-db8e043e5d64.png)
太感谢啦，升级了pip就可以安装了
请原谅我，我还是一个勤学好问的孩子，您就是我学习的榜样~
