### ISSUE TITLE
转换为二进制文件，特别占内存

### ISSUE THREAD

**Issue by wenku1992abc** [yeyupiaoling/VoiceprintRecognition-Tensorflow#13]
![image](https://user-images.githubusercontent.com/33471245/112608381-38214180-8e55-11eb-8b5a-3ef1e888bbc6.png)
请问下训练集10M转换为二进制TFrecord就变成6G多了
为什么二进制文件那么大啊？内存都有可能不够了
训练大数据的梦想也变得奢侈了~
大数据train.txt有100M,这样算下来需要600G的二进制文件存储内存！

**Comment by yeyupiaoling** [comment]
@wenku1992abc 麻烦你看下代码吧

**Comment by wenku1992abc** [comment]
> @wenku1992abc 麻烦你看下代码吧

嗯嗯，有看代码，就是提取了wav特征转换为二进制嘛，还有就是不够的补0

**Comment by wenku1992abc** [comment]
不好意思哈~
