### ISSUE TITLE
你好，这个文件怎么生成的啊

### ISSUE THREAD

**Issue by xuboot** [yeyupiaoling/VoiceprintRecognition-Tensorflow#18]
![image](https://user-images.githubusercontent.com/54123895/155870683-d0b3a25a-050c-4a1a-8bf4-6def37f4a7b4.png)

**Comment by yeyupiaoling** [comment]
训练生成的。你也可以下载。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月27日(周日) 下午2:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yeyupiaoling/VoiceprintRecognition-Tensorflow] 你好，这个文件怎么生成的啊 (Issue #18)




 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xuboot** [comment]
大佬你好，我想说如果有有几时万的歌曲需要对比需要怎么做呢，其实我需要做版权和听歌识曲的功能，我发现训练的模型出来两首歌对比确实很准，本来我看了shazam的论文，它是指把所有音乐以指纹的方式写入数据库里，然后用户输入一首歌，或者唱一首歌，可以匹配出来这首歌，但是没有方向感,同时也看了[dejavu](https://github.com/worldveil/dejavu)这个项目

**Comment by yeyupiaoling** [comment]
我是个是说话人识别，歌曲不知道能不能用这个方法做，没研究过。

**Comment by xuboot** [comment]
对比两首歌也很准
