### ISSUE TITLE
大佬，我截取傅里叶片段时间生成的特征相似度不准啊，又没有优化的思路呢，或者我截取整个傅里叶变换的时间，作为特征，但是这种整个傅里叶变化的话，处理起来特别慢，不知道你的模型是否可以优化，还是再现有的代码的基础上优化呢

### ISSUE THREAD

**Issue by xuboot** [yeyupiaoling/VoiceprintRecognition-Tensorflow#21]

**Comment by xuboot** [comment]
因为你默认的spec_len=257，也就是截取用户的1025 * 音频傅里叶变换的时间（spec_len=257 默认是这个）= 1025 * 257 的矩阵

**Comment by xuboot** [comment]
我随便截取就不行，不过截取整个傅里叶时间作为特征内存会炸掉，内存不够，同时又慢，截取傅里叶段的话匹配的结果不太好，不知道咋整

**Comment by xuboot** [comment]
同时大佬，为啥不用采用的mfcc 直接出特征呢

**Comment by yeyupiaoling** [comment]
可以安装PaddlePaddle版本，我用来比较好的模型：https://github.com/yeyupiaoling/VoiceprintRecognition-PaddlePaddle

**Comment by yeyupiaoling** [comment]
我不知道你是怎么截取的

**Comment by yeyupiaoling** [comment]
mfcc会丢失比较多的特征，这个比较适合语音识别。声纹识别用梅尔频谱比较好。个人觉得

**Comment by xuboot** [comment]
我们更多的场景是音乐版权的处理,其实我的需求就是,这个怎么说呢,就是10万原创首歌,用户随意截取高潮部分,匹配相似歌曲,原创3分钟,他可能随意截取50秒,根据一个截取的线上的url音频连接,然后匹配到相似的音乐
1.我看你代码里,设置spec_len=257  随机截取#     rand_time = np.random.randint(0, freq_time - spec_len)
    #     spec_mag = mag[:,rand_time:rand_time + spec_len],如果这段代码历史特征写入数据库,那么翻唱的截取规则就不同了,同时因为整首歌傅立叶变换时间太长了,那么整个矩阵就很大,1025 * 110000,这是三分钟的歌曲的,如果我在源音频里做截取,那么,傅立叶的矩阵都是不同的


整个矩阵就不同,截取的就不同,那么用户截取音频的下我在随意截取前0-10,10-20,20-30,特征去匹配数据库,多次运行相似度的结果一会90以上一会没有

**Comment by yeyupiaoling** [comment]
嗯嗯，按照你这种截取，应该也行。我这个是声纹识别，所以音频只有几秒钟，全部音频读取也不会有什么问题。
