### ISSUE TITLE
关于train.py

### ISSUE THREAD

**Issue by heyinwong** [yeyupiaoling/VoiceprintRecognition-Tensorflow#22]
请问出现 AttributeError: 'MirroredStrategy' object has no attribute 'experimental_run_v2' 要怎么解决？

**Comment by yeyupiaoling** [comment]
在哪一行出现的，tensorflow版本有没有对应上

**Comment by heyinwong** [comment]
啊谢谢回复，当时解决问题后忘记关掉issue了。确实是tensorflow 版本的问题。2.3之后对应的api改了所以把对应error的代码改成run就正常了。
