### ISSUE TITLE
关于训练模型时机器配置的问题

### ISSUE THREAD

**Issue by YouCun-Official** [yeyupiaoling/VoiceprintRecognition-Tensorflow#25]
我在autoDL上租用了一个10核CPU，2卡GPU的云服务器进行模型训练，结果需要3-4天。想请问一下作者大大当初训练模型时候的配置是怎么样的呢？可以14个小时就训练完毕
![image](https://user-images.githubusercontent.com/123357725/213989500-c3217881-523b-4c4f-9b5f-d28faa7c2b31.png)
![image](https://user-images.githubusercontent.com/123357725/213989543-486b2173-35dd-49a5-99eb-b039596d6576.png)

**Comment by yeyupiaoling** [comment]
什么GPU？估计是预处理跟不上。
我建议你用Pytorch版本或者PaddlePaddle版本，这个的develop分支，在A100可以在3个多小时训练完成
