### ISSUE TITLE
导入模型报错

### ISSUE THREAD

**Issue by HUSTJunshuang** [yeyupiaoling/VoiceprintRecognition-Tensorflow#4]
`python infer_contrast.py `
`Traceback (most recent call last):`
`  File "infer_contrast.py", line 8, in <module>`
`    model = tf.keras.models.load_model('models/resnet.h5')`
`  File "/home/***/anaconda3/envs/VR/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py",`
`line 146, in load_model`
`    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)`
`  File "/home/***/anaconda3/envs/VR/lib/python3.7/site-``packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5`
`    model_config = json.loads(model_config)`
`AttributeError: 'str' object has no attribute 'decode'`

**Comment by yeyupiaoling** [comment]
@HUSTJunshuang 你检查一下文件路径是否正确，文件是否存在。

**Comment by charlesXu86** [comment]
> `python infer_contrast.py `
> `Traceback (most recent call last):`
> ` File "infer_contrast.py", line 8, in <module>`
> ` model = tf.keras.models.load_model('models/resnet.h5')`
> ` File "/home/***/anaconda3/envs/VR/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py",`
> `line 146, in load_model`
> ` return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)`
> `` File "/home/***/anaconda3/envs/VR/lib/python3.7/site-``packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5 ``
> ` model_config = json.loads(model_config)`
> `AttributeError: 'str' object has no attribute 'decode'`

你这个是hdf5包的版本问题

**Comment by HUSTJunshuang** [comment]
> @HUSTJunshuang 你检查一下文件路径是否正确，文件是否存在。

都没问题

**Comment by HUSTJunshuang** [comment]
> > `python infer_contrast.py `
> > `Traceback (most recent call last):`
> > ` File "infer_contrast.py", line 8, in <module>`
> > ` model = tf.keras.models.load_model('models/resnet.h5')`
> > ` File "/home/***/anaconda3/envs/VR/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py",`
> > `line 146, in load_model`
> > ` return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)`
> > ` File "/home/***/anaconda3/envs/VR/lib/python3.7/site-`packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5 ``
> > ` model_config = json.loads(model_config)`
> > `AttributeError: 'str' object has no attribute 'decode'`
> 
> 你这个是hdf5包的版本问题

请问hdf5的包应该要哪个版本的呢   能问下怎么看出来的吗 @charlesXu86

**Comment by charlesXu86** [comment]
> > > `python infer_contrast.py `
> > > `Traceback (most recent call last):`
> > > ` File "infer_contrast.py", line 8, in <module>`
> > > ` model = tf.keras.models.load_model('models/resnet.h5')`
> > > ` File "/home/***/anaconda3/envs/VR/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py",`
> > > `line 146, in load_model`
> > > ` return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)`
> > > ` File "/home/***/anaconda3/envs/VR/lib/python3.7/site-`packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5 ``
> > > ` model_config = json.loads(model_config)`
> > > `AttributeError: 'str' object has no attribute 'decode'`
> > 
> > 
> > 你这个是hdf5包的版本问题
> 
> 请问hdf5的包应该要哪个版本的呢 能问下怎么看出来的吗 @charlesXu86

pip install h5py==2.10

**Comment by HUSTJunshuang** [comment]
> > > > `python infer_contrast.py `
> > > > `Traceback (most recent call last):`
> > > > ` File "infer_contrast.py", line 8, in <module>`
> > > > ` model = tf.keras.models.load_model('models/resnet.h5')`
> > > > ` File "/home/***/anaconda3/envs/VR/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py",`
> > > > `line 146, in load_model`
> > > > ` return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)`
> > > > ` File "/home/***/anaconda3/envs/VR/lib/python3.7/site-`packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5 ``
> > > > ` model_config = json.loads(model_config)`
> > > > `AttributeError: 'str' object has no attribute 'decode'`
> > > 
> > > 
> > > 你这个是hdf5包的版本问题
> > 
> > 
> > 请问hdf5的包应该要哪个版本的呢 能问下怎么看出来的吗 @charlesXu86
> 
> pip install h5py==2.10

谢谢，我去试试

**Comment by HUSTJunshuang** [comment]
> > > > `python infer_contrast.py `
> > > > `Traceback (most recent call last):`
> > > > ` File "infer_contrast.py", line 8, in <module>`
> > > > ` model = tf.keras.models.load_model('models/resnet.h5')`
> > > > ` File "/home/***/anaconda3/envs/VR/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py",`
> > > > `line 146, in load_model`
> > > > ` return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)`
> > > > ` File "/home/***/anaconda3/envs/VR/lib/python3.7/site-`packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5 ``
> > > > ` model_config = json.loads(model_config)`
> > > > `AttributeError: 'str' object has no attribute 'decode'`
> > > 
> > > 
> > > 你这个是hdf5包的版本问题
> > 
> > 
> > 请问hdf5的包应该要哪个版本的呢 能问下怎么看出来的吗 @charlesXu86
> 
> pip install h5py==2.10

  大佬，解决了，请问你是怎么看出来是版本的问题的呀，有没有啥秘诀能传授给我这个小白吗@charlesXu86

**Comment by charlesXu86** [comment]
你加我qq吧，997562867


Thanks&Best Regards.
Charles


在2021年02月3日 23:22，HUSTJunshuang<notifications@github.com> 写道：

python infer_contrast.py
Traceback (most recent call last):
File "infer_contrast.py", line 8, in <module>
model = tf.keras.models.load_model('models/resnet.h5')
File "/home/***/anaconda3/envs/VR/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py",
line 146, in load_model
return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
File "/home/***/anaconda3/envs/VR/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5 ``
model_config = json.loads(model_config)
`AttributeError: 'str' object has no attribute 'decode'`

你这个是hdf5包的版本问题

请问hdf5的包应该要哪个版本的呢 能问下怎么看出来的吗 @charlesXu86

pip install h5py==2.10

大佬，解决了，请问你是怎么看出来是版本的问题的呀，有没有啥秘诀能传授给我这个小白吗@charlesXu86
