### ISSUE TITLE
内容有关的还是内容无关？

### ISSUE THREAD

**Issue by CDisbettermen** [yeyupiaoling/VoiceprintRecognition-Tensorflow#5]
你好  你这是和说话内容有关的说话人识别demo？数据集如果和语料库不是一个内容，那这cos值是不是会没有意义了呢，这threshold要自己不断尝试了吗？小白求教

**Comment by yeyupiaoling** [comment]
@CDisbettermen 可以不一样的，模型是学习他们的声纹。但是理论上来说，内容一样会更好。
