### ISSUE TITLE
请问下这个是不是通用的声纹识别模型？

### ISSUE THREAD

**Issue by wenku1992abc** [yeyupiaoling/VoiceprintRecognition-Tensorflow#7]
问题如上
该模型是不是通用的声纹识别模型？
需不需要用其他数据进行训练了

**Comment by yeyupiaoling** [comment]
@wenku1992abc 这个只是一个普通卷积神经网络，你可以各种的卷积神经网络。你说的其他数据是什么意思？就项目提供的数据集就可以，想模型 更好，可以使用更多的模型

**Comment by wenku1992abc** [comment]
> @wenku1992abc 这个只是一个普通卷积神经网络，你可以各种的卷积神经网络。你说的其他数据是什么意思？就项目提供的数据集就可以，想模型 更好，可以使用更多的模型

嗯嗯，我有从头训练一个模型，用的项目提供的数据。可训练了一天一夜了竟然还没有结束。我盯了好久，accuracy没有变化了一直是0.952652。所以，手动给他停止了。
利用最后终止时的那个resnet.h5模型进行infer_contrast，测试了几遍我自己的录音，发现特别容易辨识错误。
于是，换成你提供的可供下载的resnet.h5，效果有提升，可还是不够理想。两个相同的speaker说的话，还是判断不通过，不是同一个人，几率挺高的。
训练完毕，最后模型infer项目提供的数据集以外的音档准确度怎么衡量呢？0.952652是在训练集，验证集上得到的准确度吧。

**Comment by yeyupiaoling** [comment]
@wenku1992abc 训练的进度你可以看是到多少个epoch了，默认是500。这个准确率是训练模型分类的准确率，如果是想更好的效果，需要更多的人，提高模型泛化能。你看人脸识别都是用好几千人，几十万张照片的。

**Comment by wenku1992abc** [comment]
> @wenku1992abc 训练的进度你可以看是到多少个epoch了，默认是500。这个准确率是训练模型分类的准确率，如果是想更好的效果，需要更多的人，提高模型泛化能。你看人脸识别都是用好几千人，几十万张照片的。

了解了。
那数据集需要做VAD处理吗？在此code是未经VAD处理的对吗？

**Comment by yeyupiaoling** [comment]
@wenku1992abc https://github.com/yeyupiaoling/VoiceprintRecognition-Tensorflow/blob/9a182c101f970fba1519c667144515ef0757cea5/create_data.py#L42

**Comment by wenku1992abc** [comment]
> @wenku1992abc
> 
> https://github.com/yeyupiaoling/VoiceprintRecognition-Tensorflow/blob/9a182c101f970fba1519c667144515ef0757cea5/create_data.py#L42

哇，感谢感谢！

**Comment by wenku1992abc** [comment]
> @wenku1992abc 训练的进度你可以看是到多少个epoch了，默认是500。这个准确率是训练模型分类的准确率，如果是想更好的效果，需要更多的人，提高模型泛化能。你看人脸识别都是用好几千人，几十万张照片的。
![image](https://user-images.githubusercontent.com/33471245/111927323-4c7adc80-8aeb-11eb-863e-2414b4354284.png)
这个能看出多少epoch吗？

**Comment by yeyupiaoling** [comment]
@wenku1992abc 看不出来

**Comment by wenku1992abc** [comment]
> @wenku1992abc 看不出来

再请教一个问题哦
如上图所示
每个batch的Loss 0.000085,但是Test的Loss却是0.763253；Loss为何差异那么大？
这个是不是说明在验证集上效果比较好，但是在测试集上的效果没那么好是吗？

**Comment by yeyupiaoling** [comment]
@wenku1992abc 是的，这个是过拟合了。

**Comment by wenku1992abc** [comment]
> @wenku1992abc 是的，这个是过拟合了。

那请问下我需要怎么处理呢？

**Comment by yeyupiaoling** [comment]
1、增加数据
2、使用更好的模型
3、使用正则函数

具体上网查

**Comment by wenku1992abc** [comment]
> 1、增加数据
> 2、使用更好的模型
> 3、使用正则函数
> 
> 具体上网查

谢谢啦~
