### ISSUE TITLE
请帮忙看下，数据是否处理有问题？

### ISSUE THREAD

**Issue by wenku1992abc** [yeyupiaoling/VoiceprintRecognition-Tensorflow#9]
![image](https://user-images.githubusercontent.com/33471245/111963138-232f7000-8b2e-11eb-9d5d-38f27de074e6.png)
![image](https://user-images.githubusercontent.com/33471245/111963341-5c67e000-8b2e-11eb-8beb-337358eabe07.png)
![image](https://user-images.githubusercontent.com/33471245/111963195-32aeb900-8b2e-11eb-9841-4d53ccb5a03c.png)
这个label很怪异,train.txt的文件

**Comment by yeyupiaoling** [comment]
这个列表好像不对，你是用程序生成的吗？可能是读取的时候，文章顺序变了。我有空改一下
https://github.com/yeyupiaoling/VoiceprintRecognition-Tensorflow/blob/9a182c101f970fba1519c667144515ef0757cea5/create_data.py#L70-L90

**Comment by wenku1992abc** [comment]
> 这个列表好像不对，你是用程序生成的吗？可能是读取的时候，文章顺序变了。我有空改一下
> https://github.com/yeyupiaoling/VoiceprintRecognition-Tensorflow/blob/9a182c101f970fba1519c667144515ef0757cea5/create_data.py#L70-L90

是用这个代码生成的
只需要修改一下label的生成就好了是吧？
那个P000159I代表这个speaker label是159还是159I？

**Comment by wenku1992abc** [comment]
数据集有个menta的文件有说speaker label
谢谢啦！
